name: Thorough Review
on:
  pull_request_review:
    types: [submitted]

jobs:
  comment:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Fetch GIF
        id: fetch-gif
        if: github.event.review.state == 'approved'
        uses: fjogeleit/http-request-action@v1.12.0
        with:
          url: 'https://api.giphy.com/v1/gifs/random?tag=lgtm&api_key=${{ secrets.GIPHY_API_KEY }}'
          method: 'GET'
          
      - name: Post GIF
        if: ${{ fromJson(steps.fetch-gif.outputs.response).data.embed_url }}
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            
            await github.rest.pulls.createReview({
              owner,
              repo,
              pull_number: ${{ github.event.pull_request.id }},
              body: '![](${{ fromJson(steps.fetch-gif.outputs.response).data.embed_url }})',
              comments: [],
            })
